name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build STM32
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: Install dependencies (ARM GCC, make, etc.)
      run: sudo apt install gcc-arm-none-eabi
    - name: make
      run: cd stm32l475/stm32_test/Debug; make main-build
