name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build STM32
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (ARM GCC, make, etc.)
      run: sudo apt install gcc-arm-none-eabi
    - name: make
      run: cd stm32l475/stm32_test/Debug; make main-build
    - name: test
      run: sudo gem install ceedling; sudo apt install gcovr; cd stm32l475/stm32_test/Debug/unit_test; ceedling test:all gcov:all
